### ISSUE TITLE
Reading monthly data

### ISSUE THREAD

**Issue by jeenriquez** [PORTAL-CEOS/ANHALIZE#2]
Hey @luizhdasilva , 
Lets talk about these lines of code:
```
if monthly_mean:
    print('---------------------------')
    data_path = str(input('Insert monthly averaged data path: '))
```
which are [here](https://github.com/PORTAL-CEOS/ANHALIZE/blob/63a1d9d8cef88831a97c494d78c19b2e8eef8bd1/anhalyze/anhalyze_utils.py#L202C25-L202C25). 

Maybe we can find another way to read the monthly data, first I need to understand more about the data itself, and if there is a naming convention to save these files. I'm also wondering if this is something that can be calculated "on the fly". 

Cheers,

**Comment by jeenriquez** [comment]
Sounds good. I think we can delete those line for now. If you agree.

**Comment by luizhdasilva** [comment]
That sounds great to me. If the user wants to do monthly mean, the code should be able to average the 5-days outputs.

**Comment by jeenriquez** [comment]
Removed code. Closing issue for now.

**Comment by jeenriquez** [comment]
Removed code. Closing issue for now.
